import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { AuthService } from './auth.service';
import jsPDF from 'jspdf';

@Injectable({ providedIn: 'root' })
export class ExportService {

  constructor(private authService: AuthService) {}

  // Export Customers CSV
  exportCustomersCSV(customers: any[]) {
    const headers = ['ID', 'Name', 'Email', 'Phone', 'Address', 'Status', 'Created At'];
    const rows = customers.map(c => [
      c.id, c.name, c.email || '', c.phone || '',
      c.address || '', c.status,
      new Date(c.createdAt).toLocaleDateString()
    ]);

    const csvContent = [headers, ...rows]
      .map(row => row.map(cell => `"${cell}"`).join(','))
      .join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Customers_${new Date().toLocaleDateString()}.csv`;
    link.click();
    URL.revokeObjectURL(url);
  }

  // Export Orders PDF
  exportOrdersPDF(orders: any[], stats: any) {
    const doc = new jsPDF();
    const pink = [212, 83, 126] as [number, number, number];
    const dark = [17, 17, 20] as [number, number, number];

    // Background
    doc.setFillColor(...dark);
    doc.rect(0, 0, 210, 297, 'F');

    // Header
    doc.setFillColor(...pink);
    doc.rect(0, 0, 210, 35, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('Tenanzia', 15, 20);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text('Orders Report', 15, 29);
    doc.setFontSize(9);
    doc.text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), 155, 20);

    // Stats
    doc.setTextColor(240, 240, 242);
    doc.setFontSize(9);
    doc.text('SUMMARY', 15, 48);

    const statItems = [
      { label: 'Total Orders', value: stats.total },
      { label: 'Completed', value: stats.completed },
      { label: 'Pending', value: stats.pending },
      { label: 'Revenue', value: `$${stats.totalRevenue?.toLocaleString()}` }
    ];

    statItems.forEach((item, i) => {
      const x = 15 + (i * 47);
      doc.setFillColor(30, 30, 36);
      doc.roundedRect(x, 52, 43, 18, 2, 2, 'F');
      doc.setTextColor(102, 102, 102);
      doc.setFontSize(7);
      doc.text(item.label.toUpperCase(), x + 4, 59);
      doc.setTextColor(240, 240, 242);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.text(String(item.value), x + 4, 67);
      doc.setFont('helvetica', 'normal');
    });

    // Table Header
    doc.setFillColor(30, 30, 36);
    doc.rect(15, 78, 180, 8, 'F');
    doc.setTextColor(102, 102, 102);
    doc.setFontSize(7);
    doc.text('ORDER', 18, 84);
    doc.text('CUSTOMER', 40, 84);
    doc.text('STATUS', 100, 84);
    doc.text('TOTAL', 135, 84);
    doc.text('DATE', 165, 84);

    // Table Rows
    let y = 92;
    orders.slice(0, 25).forEach((order, i) => {
      if (i % 2 === 0) {
        doc.setFillColor(20, 20, 23);
        doc.rect(15, y - 4, 180, 9, 'F');
      }

      doc.setTextColor(240, 240, 242);
      doc.setFontSize(8);
      doc.text(`#${order.id}`, 18, y + 2);
      doc.text(order.customerName?.substring(0, 20) || '', 40, y + 2);

      const statusColor = order.status === 'Completed' ? [93, 202, 165] :
                          order.status === 'Processing' ? [127, 119, 221] :
                          order.status === 'Pending' ? [239, 159, 39] : [102, 102, 102];
      doc.setTextColor(...statusColor as [number, number, number]);
      doc.text(order.status, 100, y + 2);

      doc.setTextColor(212, 83, 126);
      doc.text(`$${order.totalAmount?.toLocaleString()}`, 135, y + 2);

      doc.setTextColor(102, 102, 102);
      doc.text(new Date(order.createdAt).toLocaleDateString(), 165, y + 2);

      y += 9;
      if (y > 270) return;
    });

    // Footer
    doc.setFillColor(...pink);
    doc.rect(0, 282, 210, 15, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(8);
    doc.text('Generated by Tenanzia — Business Management Platform', 105, 291, { align: 'center' });

    doc.save(`Orders_Report_${new Date().toLocaleDateString()}.pdf`);
  }

  // Export Revenue PDF
  exportRevenuePDF(chartData: any[], stats: any, companyName: string) {
    const doc = new jsPDF();
    const pink = [212, 83, 126] as [number, number, number];
    const dark = [17, 17, 20] as [number, number, number];

    // Background
    doc.setFillColor(...dark);
    doc.rect(0, 0, 210, 297, 'F');

    // Header
    doc.setFillColor(...pink);
    doc.rect(0, 0, 210, 35, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('Tenanzia', 15, 20);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`Revenue Report — ${companyName}`, 15, 29);
    doc.setFontSize(9);
    doc.text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), 155, 20);

    // Total Revenue Card
    doc.setFillColor(30, 30, 36);
    doc.roundedRect(15, 45, 85, 25, 3, 3, 'F');
    doc.setTextColor(102, 102, 102);
    doc.setFontSize(8);
    doc.text('TOTAL REVENUE', 20, 54);
    doc.setTextColor(212, 83, 126);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(`$${stats?.totalRevenue?.toLocaleString() || 0}`, 20, 65);

    // Completed Orders Card
    doc.setFillColor(30, 30, 36);
    doc.roundedRect(110, 45, 85, 25, 3, 3, 'F');
    doc.setTextColor(102, 102, 102);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text('COMPLETED ORDERS', 115, 54);
    doc.setTextColor(93, 202, 165);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(String(stats?.completed || 0), 115, 65);

    // Monthly Breakdown
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(102, 102, 102);
    doc.setFontSize(9);
    doc.text('MONTHLY BREAKDOWN', 15, 85);

    // Chart Bars
    const maxRevenue = Math.max(...chartData.map(d => d.revenue), 1);
    const barWidth = 25;
    const maxBarHeight = 60;

    chartData.forEach((month, i) => {
      const x = 15 + (i * 32);
      const barHeight = (month.revenue / maxRevenue) * maxBarHeight;
      const barY = 145 - barHeight;

      // Bar
      if (month.revenue > 0) {
        doc.setFillColor(...pink);
      } else {
        doc.setFillColor(30, 30, 36);
      }
      doc.roundedRect(x, barY, barWidth, barHeight || 2, 2, 2, 'F');

      // Label
      doc.setTextColor(102, 102, 102);
      doc.setFontSize(7);
      doc.text(month.label?.substring(0, 6) || '', x + 2, 152);

      // Value
      if (month.revenue > 0) {
        doc.setTextColor(212, 83, 126);
        doc.setFontSize(7);
        doc.text(`$${month.revenue?.toLocaleString()}`, x, barY - 3);
      }
    });

    // Monthly Table
    doc.setFillColor(30, 30, 36);
    doc.rect(15, 162, 180, 8, 'F');
    doc.setTextColor(102, 102, 102);
    doc.setFontSize(8);
    doc.text('MONTH', 20, 168);
    doc.text('ORDERS', 90, 168);
    doc.text('REVENUE', 140, 168);

    let y = 176;
    chartData.forEach((month, i) => {
      if (i % 2 === 0) {
        doc.setFillColor(20, 20, 23);
        doc.rect(15, y - 5, 180, 9, 'F');
      }
      doc.setTextColor(240, 240, 242);
      doc.setFontSize(8);
      doc.text(month.label || '', 20, y);
      doc.text(String(month.orders || 0), 90, y);
      doc.setTextColor(212, 83, 126);
      doc.text(`$${(month.revenue || 0).toLocaleString()}`, 140, y);
      y += 9;
    });

    // Footer
    doc.setFillColor(...pink);
    doc.rect(0, 282, 210, 15, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(8);
    doc.text('Generated by Tenanzia — Business Management Platform', 105, 291, { align: 'center' });

    doc.save(`Revenue_Report_${new Date().toLocaleDateString()}.pdf`);
  }
}